---
- name: creating alias record
  hosts: localhost
  connection: local
  tasks:
  - name: Get ELB facts
    ec2_elb_facts:
      region: ap-south-1
      names: blueGreenELB
    registers: elb_facts
  - name: creating dns record
    route53: 
      state: present
      zone: sudhanshumall.com
      record: www.sudhanshumall.com
      type: A
      value: "dualstack.{{ elb_facts.elbs.0.dns_name }}"
      alias: True
      alias_hosted_zone_id: "{{ elb_facts.elbs.0.dns_name }}"
      overwrite: yes
